function str_obsv_chc = print_table()

% Shows all observers that listed under linear dynamical system 
% Displays system dynamics and authors name along with the name of the observer

str_obsv_chc = {'Luenberger Observer for Nominal LTI Systems  [ x_dot = A x + B_u u ; y = C x + D_u u]';...
        'Robust Observer for LTI Systems with Unknown Inputs (w)  [ x_dot = A x + B_u u + B_w w ; y = C x + D_u u]';...
        'Unknown Input Observer for LTI Systems with Unknown Inputs (1) (w)  [ x_dot = A x + B_u u + B_w w ; y = C x + D_u u]';...
        'L-Infinity Observer with Unknown Inputs (w) and (v)  [ x_dot = A x + B_u u + B_w w ; y = C x + D_u u + D_v v ] ';...
        'Unknown Input Observer for LTI Systems with Unknown Inputs (2) (w) [ x_dot = A x + B_u u + B_w w ; y = C x + D_u u ] ';...
        'Unknown Input Sliding Mode Observer for LTI Systems with Unknown Inputs (w) [ x_dot = A x + B_u u + B_w w ; y = C x + D_u u ] ';...
        'Robust Observer for Uncertain LTI Systems with Unknown Inputs (w) [ x_dot = A x + B_u u + B_w w ; y = C x + D_u u] '};